import type {Metadata} from "next";
import IsLogin from "@/components/admin/IsLogin/IsLogin";
import {ReactNode} from "react";
import Dashboard from "@/components/admin/Dashboard/Dashboard";
import ThemeSwitcher from "@/components/general/ThemeSwitcher/ThemeSwitcher";
import LocaleSwitch from "@/components/admin/LocalSwitch/LocalSwitch";

import './adminRootLayout.scss'

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                       params: {locale}
                                   }: Readonly<{
    children: ReactNode;
    params: { locale: string };
}>) {
    return (
        <section>
            <IsLogin>
                <main className="container-admin-main">
                    <Dashboard />
                    <div className="container-admin-content">
                        <div className="container-admin-header">
                            <ThemeSwitcher />
                            <LocaleSwitch />
                        </div>
                        {children}
                    </div>
                </main>
            </IsLogin>
        </section>
    );
}
