import type {Metadata} from "next";
import IsLogin from "@/components/admin/IsLogin/IsLogin";
import {ReactNode} from "react";
import Dashboard from "@/components/admin/Dashboard/Dashboard";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({
                                       children,
                                       params: {locale}
                                   }: Readonly<{
    children: ReactNode;
    params: { locale: string };
}>) {
    return (
        <>
            <IsLogin>
                <main className="container-admin-main">
                    <Dashboard/>
                    {children}
                </main>
            </IsLogin>
        </>
    );
}
