import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "../globals.css";
import IsLogin from "@/components/admin/IsLogin/IsLogin";
import {ReactNode} from "react";
import Dashboard from "@/components/admin/Dashboard/Dashboard";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <IsLogin>
            <main className="container-admin-main">
                <Dashboard/>
                {children}
            </main>
        </IsLogin>
        </body>
        </html>
    );
}
