import React from "react";
import type {Metadata} from "next";
import IsLogin from "@/components/admin/IsLogin/IsLogin";
import {ReactNode} from "react";
import Sidebar from "@/components/admin/sidebar/sidebar";
import Navbar from "@/components/admin/navbar/navbar";

import styles from '@/components/admin/dashboard.module.scss';


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout(
  {
    children,
    params: {locale}
  }: Readonly<{
    children: ReactNode;
    params: { locale: string };
}>) {
    return (
      <IsLogin>
        <section className={styles.container}>
          <div className={styles.menu}>
            <Sidebar/>
          </div>
          <main className={styles.content}>
            <Navbar/>
            {children}
          </main>
        </section>
      </IsLogin>
    );
}
