import type {Metadata} from "next";
import "../../globals.css";
import NavBar from "@/components/client/Header/NavBar/NavBar";
import Header from "@/components/client/Header/Header";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <section>
            <Header/>
            {children}
        </section>
    );
}
