import type {Metadata} from "next";
import "../../globals.css";
import NavBar from "@/components/client/NavBar/NavBar";
import Header from "@/components/client/Header/Header";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Header/>
            {children}
        </>
    );
}
