name: build
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Set up QEMU
        uses: sudo docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: sudo docker/setup-buildx-action@v2
      - name: Build and push
        uses: sudo docker/build-push-action@v3
        with:
          file: Dockerfile
          push: false
          tags: user/app:latest