import type {Metadata} from "next";
import {ReactNode} from "react";
import Link from "next/link";
import MyBtn from "@/components/UI/MyBtn/MyBtn";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({
                                       children,
                                       params: {locale}
                                   }: Readonly<{
    children: ReactNode;
    params: { locale: string };
}>) {
    return (
        <section>
            <Link href={"/"}>
                users list
            </Link>
            <MyBtn
                color={"primary"}
                text={"create user"}
            />
            <MyBtn
                color={"attention"}
                text={"delete user"}
            />
            {children}
        </section>
    );
}
