import type {Metadata} from "next";
import IsLogin from "@/components/admin/IsLogin/IsLogin";
import {ReactNode} from "react";
import Dashboard from "@/components/admin/Dashboard/Dashboard";
import Link from "next/link";
import MyBtn from "@/components/UI/MyBtn/MyBtn";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({
                                       children,
                                       params: {locale}
                                   }: Readonly<{
    children: ReactNode;
    params: { locale: string };
}>) {
    return (
        <section>
            <Link href={"/"}>
                users list
            </Link>
            <MyBtn type={"submit"} text={"create user"}/>
            {children}
        </section>
    );
}
